create schema banco
use banco

-- Ordem reversa para não violar FKs
DROP TABLE IF EXISTS INVESTIMENTO;
DROP TABLE IF EXISTS MOVIMENTACAO;
DROP TABLE IF EXISTS CONTA;
DROP TABLE IF EXISTS USUARIO;

-- Tabela USUARIO
CREATE TABLE USUARIO (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(100) NOT NULL,
    EMAIL VARCHAR(150) NOT NULL UNIQUE,
    SENHA_HASH VARCHAR(255) NOT NULL,
    TIPO_USUARIO ENUM('ADMIN', 'NORMAL') NOT NULL,
    DATA_CRIACAO DATETIME DEFAULT CURRENT_TIMESTAMP
);

-- Tabela CONTA
CREATE TABLE CONTA (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    USUARIO_ID INT NOT NULL,
    SALDO DECIMAL(18,2) DEFAULT 0,
    NUMERO_CONTA VARCHAR(20) NOT NULL UNIQUE,
    TIPO_CONTA ENUM('CORRENTE', 'POUPANCA', 'DIGITAL') NOT NULL,
    DATA_ABERTURA DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (USUARIO_ID) REFERENCES USUARIO(ID)
);

-- Tabela MOVIMENTACAO
CREATE TABLE MOVIMENTACAO (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    CONTA_ID INT NOT NULL,
    TIPO_MOVIMENTACAO ENUM('ENTRADA', 'SAIDA') NOT NULL,
    VALOR DECIMAL(18,2) NOT NULL,
    DESCRICAO VARCHAR(255),
    DATA_MOVIMENTACAO DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (CONTA_ID) REFERENCES CONTA(ID)
);

-- Tabela INVESTIMENTO
CREATE TABLE INVESTIMENTO (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    CONTA_ID INT NOT NULL,
    TIPO_INVESTIMENTO VARCHAR(50) NOT NULL,
    VALOR_APLICADO DECIMAL(18,2) NOT NULL,
    DATA_APLICACAO DATETIME DEFAULT CURRENT_TIMESTAMP,
    DATA_VENCIMENTO DATETIME,
    RENDIMENTO_ESPERADO DECIMAL(18,2),
    FOREIGN KEY (CONTA_ID) REFERENCES CONTA(ID)
);
